name: Freedom
description: A PocketMine-MP plugin that frees the chat of your server from stupid Microjang reporting system.
author: inotflying
website: https://github.com/inotflying/Freedom
main: inotflying\Freedom\Main
version: 1.0.1
api: 5.0.0
